

require("__apia__.prototypes.planet.apia-map-gen")
require("__apia__.prototypes.planet.carnova-map-gen")
require("__apia__.prototypes.planet.map-gen-settings")
require("__apia__.prototypes.planet.asteroid-spawn-definitions")
require("__apia__.prototypes.planet.space-connections")
require("__apia__.prototypes.planet.planets")
require("__apia__.prototypes.tile.tiles-apia")
require("__apia__.prototypes.tile.tiles-carnova")
require("__apia__.prototypes.item")
require("__apia__.prototypes.item-groups")
require("__apia__.prototypes.technology")
require("__apia__.prototypes.entity.decoratives")
require("__apia__.prototypes.entity.plants")
require("__apia__.prototypes.entity.entities")
require("__apia__.prototypes.entity.enemies")
require("__apia__.prototypes.entity.piranha-animations")
require("__apia__.prototypes.entity.projectiles")
require("__apia__.prototypes.entity.explosions")
require("__apia__.prototypes.resources")
require("__apia__.prototypes.flying-robots")
require("__apia__.prototypes.fluid")
require("__apia__.prototypes.recipe")
require("__apia__.prototypes.remnants")
require("__apia__.prototypes.categories.recipe-category")
require("__apia__.prototypes.tips-and-tricks")
