data:extend(
{
  {
    type = "fluid",
    name = "royal-jelly",
    icon = "__apia__/graphics/icons/fluid/royal-jelly.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[apia]-a[royal-jelly]",
    default_temperature = 15,
    max_temperature = 80,
    heat_capacity = "0.01kJ",
    base_color = {0.800, 0.663, 0.506},
    flow_color = {0.753, 0.592, 0.408},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "phosphoric-acid",
    icon = "__apia__/graphics/icons/fluid/phosphoric-acid.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[apia]-a[phosphoric-acid]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.01kJ",
    base_color = {0.576, 0.431, 0.325},
    flow_color = {0.357, 0.235, 0.169},
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "blood",
    icon = "__apia__/graphics/icons/fluid/blood.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[carnova]-a[blood]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.01kJ",
    base_color = {198, 16, 0},
    flow_color = {198, 16, 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "lymph",
    icon = "__apia__/graphics/icons/fluid/lymph.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[carnova]-ba[lymph]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.01kJ",
    base_color = {151, 162, 179},
    flow_color = {151, 162, 179},
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "dirty-lymph",
    icon = "__apia__/graphics/icons/fluid/dirty-lymph.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[carnova]-bb[dirty-lymph]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.01kJ",
    base_color = {125, 158, 206},
    flow_color = {125, 158, 206},
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "glycerine",
    icon = "__apia__/graphics/icons/fluid/glycerine.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[carnova]-c[glycerine]",
    default_temperature = 15,
    max_temperature = 290,
    heat_capacity = "0.01kJ",
    base_color = {218, 188, 105},
    flow_color = {218, 188, 105},
    auto_barrel = true,
  },
})
